# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

os: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

# Travis advances the master-tot tag to current top of the tree after
# each push into the master branch, because it relies on that tag to
# upload build artifacts to the master-tot release. This will cause
# double testing for each push on Appveyor: one for the push, one for
# the tag advance. Disable testing tags.
skip_tags: true

clone_depth: 5

matrix:
  fast_finish: true # Show final status immediately if a test fails.

install:
  - git clone https://github.com/KhronosGroup/SPIRV-Tools.git External/spirv-tools
  - git clone https://github.com/KhronosGroup/SPIRV-Cross.git External/spirv-cross
  - git clone https://github.com/KhronosGroup/SPIRV-Headers.git External/spirv-tools/external/spirv-headers
# scripts that run after cloning repository

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - mkdir build && cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config %CONFIGURATION% --target install
  # For debug build, the generated dll has a postfix "d" in its name.
  - ps: >-
      If ($env:configuration -Match "Debug") {
        $env:SUFFIX="d"
      } Else {
        $env:SUFFIX=""
      }
  - cd install
  # Zip all glslang artifacts for uploading and deploying
  - 7z a glslang-"%PLATFORM%"-"%CONFIGURATION%".zip
    include\glslang\*
    include\SPIRV\*
    lib\ngfx_glslang%SUFFIX%.lib
    lib\ngfx_glslang%SUFFIX%.dll

artifacts:
  - path: build\install\*.zip
    name: artifacts-zip
